In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
data = pd.read_csv('../data/HW1.train.csv')

data.shape
data.head()

,id,AL,AK,AZ,AR,CA,CO,CT,FL,GA,...,restaurant.2,spent_time.2,large_event.2,public_transit.2,anxious.2,depressed.2,felt_isolated.2,worried_become_ill.2,worried_finances.2,tested_positive.2
0,0,1,0,0,0,0,0,0,0,0,...,23.812411,43.430423,16.151527,1.602635,15.409449,12.088688,16.702086,53.991549,43.604229,20.704935
1,1,1,0,0,0,0,0,0,0,0,...,23.682974,43.196313,16.123386,1.641863,15.230063,11.809047,16.506973,54.185521,42.665766,21.292911
2,2,1,0,0,0,0,0,0,0,0,...,23.593983,43.362200,16.159971,1.677523,15.717207,12.355918,16.273294,53.637069,42.972417,21.166656
3,3,1,0,0,0,0,0,0,0,0,...,22.576992,42.954574,15.544373,1.578030,15.295650,12.218123,16.045504,52.446223,42.907472,19.896607
4,4,1,0,0,0,0,0,0,0,0,...,22.091433,43.290957,15.214655,1.641667,14.778802,12.417256,16.134238,52.560315,43.321985,20.178428

In [3]:
for value, keys in enumerate(data.columns.values.tolist()):
    if value > 40:
        print(value - 1, keys)

40 cli
41 ili
42 hh_cmnty_cli
43 nohh_cmnty_cli
44 wearing_mask
45 travel_outside_state
46 work_outside_home
47 shop
48 restaurant
49 spent_time
50 large_event
51 public_transit
52 anxious
53 depressed
54 felt_isolated
55 worried_become_ill
56 worried_finances
57 tested_positive
58 cli.1
59 ili.1
60 hh_cmnty_cli.1
61 nohh_cmnty_cli.1
62 wearing_mask.1
63 travel_outside_state.1
64 work_outside_home.1
65 shop.1
66 restaurant.1
67 spent_time.1
68 large_event.1
69 public_transit.1
70 anxious.1
71 depressed.1
72 felt_isolated.1
73 worried_become_ill.1
74 worried_finances.1
75 tested_positive.1
76 cli.2
77 ili.2
78 hh_cmnty_cli.2
79 nohh_cmnty_cli.2
80 wearing_mask.2
81 travel_outside_state.2
82 work_outside_home.2
83 shop.2
84 restaurant.2
85 spent_time.2
86 large_event.2
87 public_transit.2
88 anxious.2
89 depressed.2
90 felt_isolated.2
91 worried_become_ill.2
92 worried_finances.2
93 tested_positive.2

In [10]:
with open("../data/HW1.train.csv", 'r') as f:
    csvData = list(csv.reader(f))
    csvData = np.array(csvData[1:])[:, 1:].astype(float)

In [11]:
feats = list(range(40, 93))
csvData = csvData[:, feats]
pd.DataFrame(csvData)

,0,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,52
0,0.814610,0.771356,25.648907,21.242063,84.644672,13.462475,36.519841,63.139094,23.835119,44.726055,...,62.434539,23.812411,43.430423,16.151527,1.602635,15.409449,12.088688,16.702086,53.991549,43.604229
1,0.838995,0.807767,25.679101,21.280270,84.005294,13.467716,36.637887,63.318650,23.688882,44.385166,...,62.024517,23.682974,43.196313,16.123386,1.641863,15.230063,11.809047,16.506973,54.185521,42.665766
2,0.897802,0.887893,26.060544,21.503832,84.438618,13.038611,36.429119,62.434539,23.812411,43.430423,...,62.116842,23.593983,43.362200,16.159971,1.677523,15.717207,12.355918,16.273294,53.637069,42.972417
3,0.972842,0.965496,25.754087,21.016210,84.133873,12.581952,36.416557,62.024517,23.682974,43.196313,...,61.294809,22.576992,42.954574,15.544373,1.578030,15.295650,12.218123,16.045504,52.446223,42.907472
4,0.955306,0.963079,25.947015,20.941798,83.995931,12.938675,37.014578,62.116842,23.593983,43.362200,...,60.664482,22.091433,43.290957,15.214655,1.641667,14.778802,12.417256,16.134238,52.560315,43.321985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1.957777,2.010447,46.405397,40.567919,88.561020,9.020903,25.806140,49.346258,16.273795,32.757515,...,48.885082,15.871650,31.609763,8.956304,1.693456,19.289353,14.732485,21.669891,71.149370,51.574996
1996,2.137150,2.168533,46.538306,40.586438,88.753964,8.897227,26.523309,49.218498,16.214493,32.350572,...,48.748078,16.004232,31.758959,9.465311,1.695143,19.338434,14.528597,21.533022,70.969310,51.813714
1997,2.060483,2.132941,46.945265,40.990416,88.869914,8.574493,27.534628,48.885082,15.871650,31.609763,...,48.848409,16.156748,31.279531,9.193762,1.723249,20.008479,14.790622,21.414518,70.727949,52.093531
1998,2.067570,2.142550,46.543298,40.468735,88.753084,8.440412,28.354813,48.748078,16.004232,31.758959,...,49.662878,16.493595,30.859297,9.418017,1.727117,20.169113,14.990215,21.124113,70.694471,51.854969
1999,2.079359,2.146266,46.943841,40.724343,88.955924,8.298833,28.993671,48.848409,16.156748,31.279531,...,49.353827,16.378941,30.643177,9.744927,1.697761,20.363297,14.695019,20.938605,70.686935,51.354729